name:                shark-game
version:             0.1.0.0
github:              "knitHacker/shark-game"
license:             BSD3
author:              "Lianne Lairmore"
maintainer:          "lianne.lairmore@gmail.com"
copyright:           "2022 Lianne Lairmore"

extra-source-files:
- README.md
- ChangeLog.md
- data/configs/*.yaml
- assets/images/*.png
- assets/fonts/*.ttf

data-files:
- data/configs/*.yaml
- assets/images/*.png
- assets/fonts/*.ttf

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/knitHacker/shark-game#readme>

dependencies:
- base >= 4.7 && < 5


internal-libraries:
  shark-game-collision:
    source-dirs: src/collision
    dependencies:
    - containers >= 0.6.4.1

  shark-game-core:
    source-dirs: src/game
    dependencies:
    - sdl2 >= 2.5.5.1
    - sdl2-image >= 2.1.0.0
    - sdl2-ttf
    - text
    - mtl >= 2.2.2
    - mwc-random
    - containers >= 0.6.4.1
    - aeson >= 2.0.3.0
    - yaml >= 0.11.8.0
    - directory >= 1.3.6.0
    - time
    - vector
    - data-default
    - filepath

  shark-game-tools:
    source-dirs: tools/common
    dependencies:
    - shark-game-core
    - vector
    - containers
    - text
    - mwc-random

executables:
  shark-game:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    when:
    - condition: os(windows)
      ghc-options:
      - -optl-mwindows
    dependencies:
    - shark-game-core

  preview:
    main:                Main.hs
    source-dirs:         tools/preview
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    when:
    - condition: os(windows)
      ghc-options:
      - -optl-mwindows
    dependencies:
    - shark-game-core
    - shark-game-tools

  generate-save:
    main:                Main.hs
    source-dirs:         tools/generate-save
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    when:
    - condition: os(windows)
      ghc-options:
      - -optl-mwindows
    dependencies:
    - shark-game-core
    - shark-game-tools

tests:
  shark-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shark-game-core
    - shark-game-tools
    - hspec
