name:                shark-game
version:             0.1.0.0
github:              "knitHacker/shark-game"
license:             BSD3
author:              "Lianne Lairmore"
maintainer:          "lianne.lairmore@gmail.com"
copyright:           "2022 Lianne Lairmore"

extra-source-files:
- README.md
- ChangeLog.md
- data/configs/*.json
- assets/images/*.png
- assets/fonts/*.ttf

data-files:
- data/configs/game.json
- data/configs/textures.json
- data/configs/shark_game.json
- assets/images/arrow.png
- assets/images/nurse_shark.png
- assets/images/blue_shark.png
- assets/images/shark_placeholder.png
- assets/images/empty_net_white.png
- assets/images/boat_default.png
- assets/fonts/InsightSansSSi.ttf
- assets/fonts/saxmono.ttf

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/knitHacker/shark-game#readme>

dependencies:
- base >= 4.7 && < 5
- transformers >= 0.5.6.2
- sdl2 >= 2.0.6
- sdl2-image >= 2.1.0.0
- sdl2-ttf
- text
- mtl >= 2.2.2
- random >= 1.2.1
- mwc-random
- containers >= 0.6.4.1
- aeson >= 2.0.3.0
- directory >= 1.3.6.0
- time
- lens
- lens-aeson
- vector
- data-default
- filepath

library:
  source-dirs: src

executables:
  shark-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - shark-game

tests:
  shark-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shark-game
